SELECT DATE
     , AD_ID
     , ACTION_TYPE
FROM FIVETRAN_DATABASE.FACEBOOK_ADS.ADS_INSIGHTS_ACTIONS
GROUP BY DATE
     , AD_ID
     , ACTION_TYPE

UNION

SELECT DATE
     , AD_ID
     , ACTION_TYPE
FROM FIVETRAN_DATABASE.FACEBOOK_ADS.ADS_INSIGHTS_CONVERSIONS
GROUP BY DATE
     , AD_ID
     , ACTION_TYPE
