SELECT CAST(F.DATE AS DATE) AS DATE
     , G.ACCOUNT
     , G.CAMPAIGN
     , G.ADSET
     , G.AD
     , F.AD_ID AS AD_ID
     , F.ACTION_TYPE AS CONVERSIONNAME
     , C.CNT AS DIVIDEND
     , SUM(G.SPEND) AS SPEND_RAW
     , SUM(G.IMPRESSIONS) IMPRESSIONS_RAW
     , SUM(G.CLICKS) AS CLICKS_RAW
     , SUM(COALESCE(VALUE, 0)) AS ALLCONV
FROM FIVETRAN_DATABASE.FACEBOOK_ADS.ADS_INSIGHTS_ACTIONS F
JOIN {{ ref('v_stg_facebook_spend') }} G ON F.AD_ID = G.AD_ID AND F.DATE = G.DATE
JOIN {{ ref('v_stg_facebook_distinct_actions') }} C ON F.DATE = C.DATE AND F.AD_ID = C.AD_ID
GROUP BY F.DATE
     , G.ACCOUNT
     , G.CAMPAIGN
     , G.ADSET
     , G.AD
     , F.AD_ID
     , F.ACTION_TYPE
     , C.CNT