 {{config(materialized = "table")}} 

SELECT AI.NETWORK_NAME
     , AI.CAMPAIGN_NAME
     , AI.ADGROUP_NAME
     , CAST(AI.INSTALL_DATE AS DATE) AS INSTALL_DATE
     , COUNT(DISTINCT AI.IDFV) AS INSTALLS
     , COUNT(DISTINCT M.AMPLITUDE_DEVICE_ID) AS MATCHED_DEVICES
     
     -- Registration events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'Registered' THEN M.AMPLITUDE_DEVICE_ID END) AS REGISTERED_USERS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'FTE_REGISTERED' THEN M.AMPLITUDE_DEVICE_ID END) AS FTE_REGISTERED_USERS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'NewPlayerCreation_Success' THEN M.AMPLITUDE_DEVICE_ID END) AS NEW_PLAYER_SUCCESS
     
     -- Revenue events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'Revenue' THEN M.AMPLITUDE_DEVICE_ID END) AS REVENUE_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'Revenue' THEN 1 ELSE 0 END) AS REVENUE_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'PurchaseSuccess' THEN M.AMPLITUDE_DEVICE_ID END) AS PURCHASE_SUCCESS_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'PurchaseSuccess' THEN 1 ELSE 0 END) AS PURCHASE_SUCCESS_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'PurchaseComplete' THEN M.AMPLITUDE_DEVICE_ID END) AS PURCHASE_COMPLETE_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'PurchaseComplete' THEN 1 ELSE 0 END) AS PURCHASE_COMPLETE_EVENTS
     
     -- Pro Shop events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'ProShopPurchase' THEN M.AMPLITUDE_DEVICE_ID END) AS PROSHOP_PURCHASE_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'ProShopPurchase' THEN 1 ELSE 0 END) AS PROSHOP_PURCHASE_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'ProShopRental' THEN M.AMPLITUDE_DEVICE_ID END) AS PROSHOP_RENTAL_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'ProShopRental' THEN 1 ELSE 0 END) AS PROSHOP_RENTAL_EVENTS
     
     -- Engagement events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'RoundStarted' THEN M.AMPLITUDE_DEVICE_ID END) AS ROUND_STARTED_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'RoundStarted' THEN 1 ELSE 0 END) AS ROUND_STARTED_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'RoundEnded' THEN M.AMPLITUDE_DEVICE_ID END) AS ROUND_ENDED_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'RoundEnded' THEN 1 ELSE 0 END) AS ROUND_ENDED_EVENTS
     
     -- Session events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'session_start' THEN M.AMPLITUDE_DEVICE_ID END) AS SESSION_START_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'session_start' THEN 1 ELSE 0 END) AS SESSION_START_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'session_end' THEN M.AMPLITUDE_DEVICE_ID END) AS SESSION_END_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'session_end' THEN 1 ELSE 0 END) AS SESSION_END_EVENTS
     
     -- Goal/Achievement events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'GoalRedeemed' THEN M.AMPLITUDE_DEVICE_ID END) AS GOAL_REDEEMED_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'GoalRedeemed' THEN 1 ELSE 0 END) AS GOAL_REDEEMED_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'GoalMilestoneClaimed' THEN M.AMPLITUDE_DEVICE_ID END) AS GOAL_MILESTONE_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'GoalMilestoneClaimed' THEN 1 ELSE 0 END) AS GOAL_MILESTONE_EVENTS
     
     -- Video Ad events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'VideoAdCompleted' THEN M.AMPLITUDE_DEVICE_ID END) AS VIDEO_AD_COMPLETED_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'VideoAdCompleted' THEN 1 ELSE 0 END) AS VIDEO_AD_COMPLETED_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'VideoAdRewarded' THEN M.AMPLITUDE_DEVICE_ID END) AS VIDEO_AD_REWARDED_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'VideoAdRewarded' THEN 1 ELSE 0 END) AS VIDEO_AD_REWARDED_EVENTS
     
     -- Coin/Tournament events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'CoinPlayClicked' THEN M.AMPLITUDE_DEVICE_ID END) AS COIN_PLAY_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'CoinPlayClicked' THEN 1 ELSE 0 END) AS COIN_PLAY_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'TournamentRoundStarted' THEN M.AMPLITUDE_DEVICE_ID END) AS TOURNAMENT_STARTED_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'TournamentRoundStarted' THEN 1 ELSE 0 END) AS TOURNAMENT_STARTED_EVENTS
     
     -- FTE (First Time Experience) events
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'FTE' THEN M.AMPLITUDE_DEVICE_ID END) AS FTE_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'FTE' THEN 1 ELSE 0 END) AS FTE_EVENTS
     , COUNT(DISTINCT CASE WHEN AE.EVENT_TYPE = 'FTECompleteSubStep' THEN M.AMPLITUDE_DEVICE_ID END) AS FTE_COMPLETE_SUBSTEP_USERS
     , SUM(CASE WHEN AE.EVENT_TYPE = 'FTECompleteSubStep' THEN 1 ELSE 0 END) AS FTE_COMPLETE_SUBSTEP_EVENTS
     
FROM {{ ref('v_stg_adjust_installs') }} AI
LEFT JOIN {{ ref('v_stg_adjust_amplitude_device_mapping') }} M 
  ON AI.IDFV = M.ADJUST_IDFV
LEFT JOIN AMPLITUDEANALYTICS_AMPLITUDE_DB_364926_SHARE.SCHEMA_726530.EVENTS_726530 AE 
  ON M.AMPLITUDE_DEVICE_ID = AE.DEVICE_ID
  AND AE.EVENT_TIME >= AI.INSTALL_DATE
WHERE AI.INSTALL_DATE >= TO_TIMESTAMP('2025-10-01')
GROUP BY AI.NETWORK_NAME
       , AI.CAMPAIGN_NAME
       , AI.ADGROUP_NAME
       , CAST(AI.INSTALL_DATE AS DATE)
ORDER BY INSTALL_DATE DESC
       , INSTALLS DESC