SELECT IDFV
     , NETWORK_NAME
     , CAMPAIGN_NAME
     , ADGROUP_NAME
     , CREATIVE_NAME
     , COUNTRY
     , TO_TIMESTAMP(INSTALLED_AT) AS INSTALL_DATE
FROM ADJUST_S3.DATA.IOS_ACTIVITY_INSTALL
WHERE IDFV IS NOT NULL
  AND INSTALLED_AT IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY IDFV ORDER BY INSTALLED_AT ASC) = 1